CI tutorial
I was following along with the continuous integration video. When i went to push upstream it was giving me 


    git branch --set-upstream-to=origin/<branch> add-ci

PS C:\Users\micha\go\src\github.com\mmcabee389\Pivottech\cmd> git push --set-upstream origin add-ci
To https://github.com/mmcabee389/Pivottech.git
error: failed to push some refs to 'https://github.com/mmcabee389/Pivottech.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

error